version: "3.3"
services:
# docker network create mynetwork
# docker run -d --name web1 --net mynetwork jmalloc/echo-server
  web:
    image: jmalloc/echo-server     
  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4 
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - 80:80
      - 8404:8404
    depends_on:
      - web

